name: Build LaTeX document
on:
  push:
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: run.tex
          working_directory: LaTeX-Documentation

      - name: List files
        run: ls LaTeX-Documentation

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: LaTeX-Documentation/run.pdf

      - name: Check if tags format matches
        run: echo "GitHub ref is ${{ github.ref }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: LaTeX-Documentation/run.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
